### ISSUE TITLE
CityJSON writer does not define the required feature types

### ISSUE THREAD

**Issue by deanhintz** [safesoftware/fme-CityJSON#38] opened 2020-01-29 18:16 UTC
Add writer currently has very limited functionality. It does not support workflows similar to how FME's CityGML's writer is used, which supports adding predefined destination feature types. The CityJSON writer currently requires a valid CityJSON file in order to add a working writer. One could add a writer with a NewFeatureType generic ftype, but if the user does not modify this to match exactly the requirements for the schema as per the spec, then writer won’t produce usable output.

I assume the general functionality should be like CityGML. For example, that is a fixed schema format, so if you have a blank destination dataset path parameter, or a path to a new output file that doesnt exist yet,, it should have the format schema defined somewhere so the output feature types can be imported into the workspace. With CityGML, the writer uses the reader schema scan to get the destination feature type definitions from the CityGML xsds. 

With Apple IMDF, I believe we have schema definition text files which the writer reads in order to define the fixed schema for the output. At the moment with CityJSON, the user is left to guess what the correct schema is for the destination. Even if they were to follow the spec closely, the chances of making a case, spacing or data type error is high. Given that FME's JSON writer does not have built in schema checks, FME would likely write the JSON out ok but other readers would probably have errors trying to read that output.

I tested the CityJSON writer in FME 2020 build 20170 and it does do some initial checks for validity. It checks that the feature type name belongs to the schema. It also complains if the feature does not have an fid or if the geometry does not have a cityjson_lod defined. However, if the feature type name is valid and there is an fid but the rest of the schema is not defined correctly, then in most cases it seems that the translation completes without error and does not write anything useful.

Example workspace showing writer test with invalid schema:
[CityJSONwriter_invalidSchemaTest.zip](https://github.com/safesoftware/fme-CityJSON/files/4129835/CityJSONwriter_invalidSchemaTest.zip)

**Comment by keithsorenson** [comment] 2020-01-30 00:22
It seems that there's an additional issue embedded in the attached workspace; The writer doesn't support the IFMEBox geometry (because it has only two explicit coordinates, and the rest are implicit?).  Output is more sensible if a BRep solid composed of faces with explicit vertices is read into the same workspace instead of the Box geometry originally created.

**Comment by hugoledoux** [comment] 2020-01-30 06:32
Cheers for feedback, this heps.

Indeed currently a new blank writer doesn't offer predefined ftype. This is something that I expect Safe employees to do as I do not know how. The current code checks for the basic things: is the name of the ftype allowed (those: https://www.cityjson.org/specs/1.0.1/#city-object) and the fid and the lod for the geometry are checked. 

The user has to guess at this moment, this is correct. We are writing the docs, which should help. However, it should be noticed that CityJSON is way more flexible than CityGML here: any ftype for an Extension (https://www.cityjson.org/specs/1.0.1/#extensions) can be written (it must start with a '+'). 

Also, I was wondering, how does GeoJSON do this? I mean, there are no predefined schema, and CityJSON is perhaps closer in philosophy to GeoJSON than to CityGML. How is the validity of a GeoJSON checked by FME? 

Since CityJSON is more flexible, I reckon that if you define a new feature and fulfill the fid, name, and you have a geometry that is allowed, then you'll create a valid CityJSON file if FME doesn't report an error. I did this by taking a shapefile of building footprint, extrude it, and generate Buildings in CityJSON.

**Comment by hugoledoux** [comment] 2020-01-30 06:37
@keithsorenson indeed the IFMEBox is not supported, you need to cast it to a solid (`IFMEBRepSolid`) for it to work.

Question for the group: should the CityJSON writer perhaps those cast on-the-fly without warning the user? I chose not too, partly because there are many types (like `IFMEMesh` and `IFMECSGSolid`) and many things can happen in the conversion. I thought it was more "FME-like" to let the user perform the conversion herself. Am I correct?

**Comment by keithsorenson** [comment] 2020-01-30 18:02
When an unsupported geometry is sent to the Writer, I would prefer an informative warning in the log to silent processing, whether that means dropping features or coercing the geometries to something supported.

**Comment by hugoledoux** [comment] 2020-01-30 18:11
of course, this is the implemented behaviour right now.

**Comment by KevinWiebe** [comment] 2020-02-01 00:45
I'll chime in on the geometry conversion topic first...
- I've seen different formats handle this case differently.  It kind of depends on what the culture of the users of that format kind of expect.  ESRI-ish users may be used to one kind of behaviour, and Oracle-ish users used to another.

1) If you want to be strict, you can stop the translation at the first unsupported geometry you see, with an error message.  Some folks like this, but in other situations this is a real pain, because they may have run a 6 hour translation they have to start all over again.

2) If you want to be a bit less strict, you can log the feature, spit out a warning message, just ignore it and continue.  Some formats do this.  It lets those who care check the logfiles, but does not stop the full translation (in case really they did not care if it was dropped).

3) If you want to be helpful, or at least try, you can do your best to "force" it into something you can handle.  Maybe with a warning message.  

Or you can provide a writer option to all of these behaviours and have the user pick which one they want.  :)

In this case, I think #3 should not be too hard, because converting from IFMEBox to IFMEBrepSolid should be easy and basically lossless.  IFMEBox has a method on it called getAsBRepSolid().
- This would not prevent the user from doing the conversion themselves before the writer, but would also be kind of a helpful "best guess" at what they'd probably want in most cases.
- A lot of the formats in FME do some variation of #3, for situations where the features are more-or-less reasonable, but not exactly.  (Like sending a polygon into a writer expecting a line.  It just silently writes out the boundary as a line.  etc.)

**Comment by KevinWiebe** [comment] 2020-02-01 01:01
I don't particularly like having GitHub issues with more than one discussion topic on them, but I'll add my comments to the main topic here, which is dealing with writer schemas and "feature types".  I've got some questions for you @hugoledoux , and then I'll know which solutions fit this situation best, and I can implement some examples.

A) When making a workspace, some writers start off with a set of FeatureTypes, and some start off blank.
- I think the basic idea in this issue is that we do not want to start of blank, right?

B) If we start off blank, or start off with a nice set of FeatureTypes on a writer, users can always delete them and get a fresh set of FeatureTypes for a writer by "importing" them from a reader or other source.
- We still want this behaviour for CityJSON, no matter what we do for starting off, right?

C) Once we have a set of FeatureTypes, some writers "lock them down" and do not allow users to add things like custom attributes or anything.  Other formats allow users to tweak them.
- For CityJSON, do we want to lock down the FeatureTypes we start off with?  Or would we want to start off with a nice canned set of FeatureTypes that conform to a plain CityJSON schema, but allow them to add custom attributes and stuff?

D) Initial FeatureTypes when adding a writer:  these are the fun decisions...
   - If there is only one set of FeatureTypes for CityJSON, the simplest way is to use the "canned schema" method in FME to take care of this for you.  I can set it up as an example if this is what we decide.  It would mean that when you drop down a CityJSON writer, it will start off with the exact same FeatureTypes to start.
  - If there is some sort of variety of FeatureTypes for a new Writer, we'd not want to use the "canned schema" mechanism of FME, but use some other more dynamic process.  Again, I can code it up quickly if this is what we want.  In this case, the writer dialog box would have some kind of "settings" (like maybe options like "plain CityJSON" or some picklist of a bunch of ADE options, or maybe links to ADE schema files or something.)  This choice is passed into the code (in a tricky way) and our CityJSON plugin will return the set of FeatureTypes appropriate to those options.  Those are the ones that will appear in the workspace once that writer is added.


After I get some answers to the things above, I'll sketch out the code for you, and you can fill in all the details and options.  I'm assuming you're going to probably want the ADE option, but I'm not sure how you'd want the user prompted for that.  A picklist of hard coded options?  Ask them for a pathname to some ADE definition file, if such exist?  Or both?  It's up to you.  We'd just want to help the user a bit rather than having them create all the FeatureTypes by hand to exactly match what a valid CityJSON file needs.

Sound good?

**Comment by hugoledoux** [comment] 2020-02-03 13:50
A) yeah I guess not empty is the best, offering from the list of standard types would be best IMO.
https://github.com/safesoftware/fme-CityJSON/blob/master/fmecityjson/fmecityjsonwriter.cpp#L69

B) yes

C) CityJSON is not very rigid for the attributes, anything goes. Complex JSON attributes are not supported at this moment (and won't be for now) but anything with a int/double/string is fine. So no lock I'd say.

D) maybe the easy option at this point? Extensions/ADEs can be written (the features, but no way to define how to reference the schema at this point), but perhaps too ambitious, and confusing, at this point to expose all gory details to the users? Your call, not mine here. But yes teh skeleton of code would help.

**Comment by hugoledoux** [comment] 2020-02-03 13:59
Right now I think I stop the conversion, but you guys decide what FME users want. Perhaps a WARN in the log is fine and I just continue with the other ones...

Conversion could be done for IFMEBox or Extrusion-type, but for some types it's "dangerous" to convert OTF without warnings, no? Like if someone uses the Nef Polyhedra types and does CSG Boolean ops, then I think the user should be fully aware of what is going one and do the conversion herself, no?

**Comment by KevinWiebe** [comment] 2020-02-04 01:24
(It is too bad there are 2 separate issues being discussed here.)
-> I think that the best thing to do with geometry conversion is to just do the best conversion you can and keep on going.  I think most of our writers try and do this.  The reason is that in a lot of cases we get users that are really really beginners.  They may read some data from IFC or Sketchup and try and write it to CItyJSON.  If it stops and tells them "Error: can't handle CSG" or something, they will have no idea what to do.  If instead we think and convert it the best way we would do it ourselves, on the fly, it will help these beginners out.  And the "experts" can always read the logfile for warnings and do it themselves if they can think of something better.  (But I would also probably not even put out any warning at all if there is only one good option of what to do.  Like converting IFMEBox to IFMEBrepSolid - we can just silently convert there, I think, no?)

**Comment by KevinWiebe** [comment] 2020-02-04 01:26
Thank you for your answer about canned schemas.
I will check in some skeleton code to start down that path.
I will also make notes on the "other" fancy way of doing things, in case we want to go that route in the future.  But mostly, just saving some notes here.

**Comment by KevinWiebe** [comment] 2020-02-06 00:28
@hugoledoux , change of plans on the schema, I think.
I put in the work to do the more simple "canned" schema, but I now don't think it is the best path forward.  It will be much harder to maintain in the future.

I'll keep these code changes on my branches, but I'll instead move forward on the more complex path.  Yes, this will make it easier to support ADE in the future, but more importantly, it will also be much easier to maintain.

The basic idea here is that FME will actually ship the cityjson schema files, and when we add a new writer in workbench, it will populate the destination FeatureTypes directly from the appropriate cityjson schema files.  Changing this behaviour will be as easy as shipping different cityjson schema files.  Does this sound ok?

**Comment by KevinWiebe** [comment] 2020-02-07 23:06
I have updated FME, and it now will ship with CityJSON schema files.

Now, I will update this plugin to use these files to populate writer FeatureTypes at startup.
If the specs ever change in the future, all we need to do is drop in new CityJSON schema files in the install directory.  Easy.

**Comment by KevinWiebe** [comment] 2020-02-12 00:51
Another time for a long story.  Sorry!

I pushed up some code that tweaks things so that the writer will auto generate correct schema files for blank workspaces, or adding fresh writers.
https://github.com/safesoftware/fme-CityJSON/pull/43

But it is a bit complicated and the work is not done, so I am hoping I can explain things a bit and @hugoledoux or @balazsdukai or someone can finish it off on your end.  You will know the final details better than I.

-> So, the goal is that when we drop down a new writer, we want valid FeatureTypes (schema) to appear, and then users can connect things up correctly if they want.  (They could also modify those as well, to add new attributes or whatever.)

The way FME does this is not very straight forward, sadly.  But I'll explain how it all hangs together.
1) The cityjson.fmf file describes how the format works, and I added a few lines in there to indicate that in this situation, when a new writer is added, FME should actually call the format's reader code (!!) and ask for all the schema features.  At the top of the cityjson.fmf file, I showed there is a way to pass any user settings you want in this process.  For now I just passed through the version number setting, but you could imagine passing through which ADE they wanted, or whatever else you may need in this situation.
2) Now, all the code I needed to add was actually in the reader class.  I know this is a bit surprising, but it works.  In this case the reader will start up and be given a special flag to know it is being used in a "helper mode" to supply schemas for when a writer is added to a workspace.  I have code that checks the reader is in this special mode `writerHelperMode_` and otherwise the reader should not change behaviour.
3) Once the reader is in this special mode, I have some ugly code that uses the CityJSON Version to look for schema info inside the FME install directory.  For example, if you picked version "1.0", it will look for schema version "1.0.1".  This is brittle code, and maybe you can make it look for the newest version of 1.0.x or something?
4) Once it finds the schema information, it will parse them all and create schema features in FME.  I just put in enough code to look for the `Metadata` FeatureType, but I guess you could add code to grab schema information for all the schema types that are appropriate.  I also hacked together the parsing and type matching, so there is a lot that can be improved with your knowledge.
5) Now, for me, when I drop in a new CityJSON writer, it automatically adds a version 1.0.1 Metadata FeatureType!  A pretty good start.

But, you may ask, how do the official CItyJSON schema files get into the FME install directory?
- All beta versions of FME will ship with them included.
- I have updated "readme" for this project to explain how you can add them manually, if you do not have the latest FME beta version.  (I suspect you may just want to copy these files into your install directories, copy the new cityjson.fmf file as well., and avoid doing a complete new fme install.)
https://github.com/safesoftware/fme-CityJSON/blob/master/README.md

I *hope* this is enough information for me to pass the torch for you to complete this work.
But I may have been unclear, and I am willing to answer any questions to get you guys going.
Let me know if you get it working!

**Comment by hugoledoux** [comment] 2020-02-17 09:41
The schemas in the folder (I'm using 2019.2) is working fine.

For now I don't see the schemas changing so having v1.0.1 hardcoded is fine (I have too many things to do to fix this, sorry).

One thing is not clear to me, it's that `writerHelperMode_`... Now the issue is that if I put a new writer, then it will always read the schemas? The options to copy from the source or others is disabled, why is that? 
![2020-02-17 at 10 38](https://user-images.githubusercontent.com/1546518/74641729-0e85e900-5172-11ea-9a2a-b2d1b32eb35d.png)

**Comment by KevinWiebe** [comment] 2020-02-28 22:19
I pushed up some code that fleshes things out more, so that the writer has an option to auto generate correct schema files for blank workspaces, when adding fresh CityJSON writers.  There is also a "None" option to start off with a blank canvas.
#46

I'll provide more screenshots and description later on how one can still use this to "copy from source" or "import from dataset" even though those options seem not available.  (One must get at them through a slightly different location for now.)

**Comment by KevinWiebe** [comment] 2020-03-04 00:33
I've had a lot of meetings with folks on our end (Dale, Dean, Ryan, etc.) and I have learned a lot about FME that I never knew before.  I've learned that CityJSON shares some of the needs that formats like IMDF, INSPIRE, and CityGML have, but that we have not always made the most easy to use settings boxes and things for those formats, so we can try to do better here.

We all discussed what the common use case scenarios for CityJSON are, and came up with 5 use cases.  These are the 4 different things that a user may want to do when he drops down a new CityJSON writer.  We want to make these all very easy to do:
a) start off blank, nothing, no feature types. User will add what they want later by hand crafting FeatureTypes on their own.
b) Start off with a basic set of FeatureTypes (to pick from) which have the main expected attributes.  (select which version of schema to start off with.)  User can customize this later by trimming down attributes or FeatureTypes, etc.
c) copy FeatureType schemas from an existing reader already in the workspace
d) copy FeatureType schemas from an existing dataset, not in the workspace

I'm not sure what workflow you or your team normally works with.  But the thinking here was that most "average" FME users would probably pick B), so that should be our default.  
Those users who are trying to convert data from a different format (like Shape) will probably prefer B), because it gives them a target to write into, and they can transform their data to fit.
Those users who are trying to read in a CityJSON file, tweak it, and write it out, may prefer option c) so they know their writer will have the exact schema as the file they are reading in.
Those users who are creating a CityJSON file of a very specific type, would want to use option d) if they have an example dataset hanging around.  They could use that to be their target schema.

I'll explain how all 4 of these options should work.

a) When you drop a new CityJSON writer into Workbench, the settings box allows you to pick "None", as shown.  Very easy to do this now.
![image](https://user-images.githubusercontent.com/18684564/75832370-ec43bc00-5d6a-11ea-944e-d01796f22fea.png)

b) If you pick "1.0.1", this is the starting schema you'd get.  This is probably what we'd have as the default.  But this is also where we need your help to polish up.  It is pretty rough.  For now, this is what you'd pick:
![image](https://user-images.githubusercontent.com/18684564/75832490-26ad5900-5d6b-11ea-8dc8-07de5c366849.png)

Then you'd get a list of FeatureTypes you could pick from.  Or select them all.
![image](https://user-images.githubusercontent.com/18684564/75832536-43499100-5d6b-11ea-9f6f-98d0ad2e09e4.png)

Then you'd get the starting schema, with appropriate attributes, something like this:
![image](https://user-images.githubusercontent.com/18684564/75832651-899ef000-5d6b-11ea-80f5-1f56f11b1a68.png)


c) Copying from an existing reader in a workspace USED to be like this:
![image](https://user-images.githubusercontent.com/18684564/75832800-fd40fd00-5d6b-11ea-9154-0af92b9d7cf2.png)
But that is gone now.  Instead, we have a different way to do it now, and in the future we will make it better.
For now, you'll need to pick "none" like in option a) and then once you have a CityJSON writer in your workspace with no FeatureTypes, pull down the "right click" menu and copy from a reader there:  (You can do all of them at once.)
![image](https://user-images.githubusercontent.com/18684564/75833017-91ab5f80-5d6c-11ea-8fb9-6cd3fdd62e48.png)

d) This is similar to c).  You start off with "None", and then pull down a menu from the top, and import a schema from an existing dataset you have on your computer somewhere.
![image](https://user-images.githubusercontent.com/18684564/75833081-c0293a80-5d6c-11ea-861f-473ec977717a.png)

**Comment by KevinWiebe** [comment] 2020-03-04 00:38
Now, what work we really would like help from your end is this.
-> Please test out the b) option.  Dropping down the default set of schemas for 1.0.1.  Do these look right?  Are the attributes about right?  Anything missing?  Anything on there that is really not needed?  Please update the code to avoid those parts of the schema, or scrape the schema JSON files deeper to get more info that is required.  Hopefully we are pretty close.
-> Look over the code I added in pull request #46.  That is some pretty ugly JSON parsing code, I know, because I have no experience with it.  Please add error checking, catching exceptions, and any other kind of JSON parsing cleanup you can think of.  I hope I did it somewhat right, but please make it a bit more robust where it needs it?  Thanks!  @hugoledoux @balazsdukai

**Comment by hugoledoux** [comment] 2020-03-05 08:51
option B works fine. The schema exposes `children` and `parents` but we mapped those to `cityjson_parents` and `cityjson_children` because those are special fields that are not attributes. Perhaps remove? Rest is fine.

Option A doesn't work for me, if I pick "none" then I get output in the console but no writer is put in the canvas. Niets, nada. I'm still using FME 2019.2 and I compiled your code under macOS.

Output console:
```
Starting translation...
                FME 2019.2.2.0 (20200103 - Build 19817 - macosx)
                        FME Database Edition (floating)
                       Temporary License: 302 days left.
                Machine host name is: x064182.citg-m.tudelft.nl
            Operating System: Mac OS X Version 10.15.3 (Build 19D76)
                 Copyright (c) 1994 - 2019, Safe Software Inc.
                               Safe Software Inc.
Creating reader for format: NULL (Nothing)
Trying to find a DYNAMIC plugin for reader named `NULL'
DYLD_LIBRARY_PATH is not set
Loaded module 'NULL' from file '/Library/FME/2019.2//plugins/null.so'
FME API version of module 'NULL' matches current internal version (3.8 20190820)
Opened mapping File /private/tmp/FME_1583398085433_16083.fmw for output
Creating reader for format: CityJSON (Tech Preview)
Trying to find a DYNAMIC plugin for reader named `CITYJSON'
Loaded module 'CITYJSON' from file '/Library/FME/2019.2//plugins/cityjson.so'
FME API version of module 'CITYJSON' matches current internal version (3.8 20190820)
CITYJSON_STARTING_SCHEMA none
Closing reader on dataset .
Closing reader on dataset .
Mapping File Generation was SUCCESSFUL
Mapping File Generation was SUCCESSFUL
FME Session Duration: 0.2 seconds. (CPU: 0.2s user, 0.0s system)
END - ProcessID: 16621, peak process memory usage: 67132 kB, current process memory usage: 67132 kB
```

**Comment by balazsdukai** [comment] 2020-03-05 14:52
**Option A** works too. I also expected a writer in my canvas as Hugo.

**Option B** crashes for me. It doesn't find the schema, where should it be? See the log below.

```
Creating reader for format: NULL (Nothing)
Trying to find a DYNAMIC plugin for reader named `NULL'
LD_LIBRARY_PATH is '/opt/fme-desktop-2019//fmecore:/opt/fme-desktop-2019/fmecore'
Loaded module 'NULL' from file '/opt/fme-desktop-2019/plugins/null.so'
FME API version of module 'NULL' matches current internal version (3.8 20190820)
Opened mapping File /tmp/FME_1583418824159_21496.fmw for output
Creating reader for format: CityJSON (Tech Preview)
Trying to find a DYNAMIC plugin for reader named `CITYJSON'
Loaded module 'CITYJSON' from file '/opt/fme-desktop-2019/plugins/cityjson.so'
FME API version of module 'CITYJSON' matches current internal version (3.8 20190820)
CITYJSON_STARTING_SCHEMA 1.0.1
Unknown setting for CityJSON writer's starting schema.
Schema file does not exist
BADNEWS: A fatal error has occurred. Check the logfile above for details virtual StatusInfo* DynamicReader::getSchema(const StringArray&, STFFeatureVector&)(foundation/pluginbuilder/pluginbuilder_cpp/dynaread.cpp:156) - virtual StatusInfo* DynamicReader::getSchema(const StringArray&, STFFeatureVector&)(foundation/pluginbuilder/pluginbuilder_cpp/dynaread.cpp:156)
Closing reader on dataset .
Closing reader on dataset .
FME Session Duration: 0.5 seconds. (CPU: 0.3s user, 0.2s system)
END - ProcessID: 21656, peak process memory usage: 18995 kB, current process memory usage: 17916 kB
A fatal error has occurred. Check the logfile above for details
Program Terminating
Translation FAILED.
Workspace generation failed.  Parameter file was /tmp/FME_1583418824159_21496.
```

**Option C** crashes for me on the [Railway data](https://3d.bk.tudelft.nl/opendata/cityjson/1.0/LoD3_Railway.json). See the log and screenshot of my Workbench below.

```
CITYJSON writer: An error occurred. FME will attempt to provide more information on the error, but this may cause the translation to be terminated
CITYJSON writer: map::at
(foundation/pluginbuilder/pluginbuilder_cpp/dynawch.cpp:188) DynaWriteChannel::putFeature(STFFeature*&)::<lambda()>
Stored 15 feature(s) to FME feature store file `./mapping_log.ffs'
FME Session Duration: 3.1 seconds. (CPU: 2.6s user, 0.4s system)
END - ProcessID: 21779, peak process memory usage: 124948 kB, current process memory usage: 75725 kB
CITYJSON writer: map::at
Program Terminating
Translation FAILED.
Warning: not all FMESessions that were created were destroyed before shutdown.  This may cause instability
```

![image](https://user-images.githubusercontent.com/7190603/75992888-f267a300-5ef8-11ea-8a3f-011f4521f809.png)

**Option D** crashes with the same error as for Hugo.

**Comment by hugoledoux** [comment] 2020-03-05 14:57
@balazsdukai you didn't read the README.txt (yesssssss I never thought I'd say this 😬). Kevin added where to put the schema files, they will be in fme2020... So b and c shouldn't crash

**Comment by hugoledoux** [comment] 2020-03-05 15:01
Build an alternative to the vaporware that is http://simstadt.eu

In Python, with cjio as backbone. Sounds feasible, innit?

**Comment by KevinWiebe** [comment] 2020-03-06 00:40
> **Option A**: it does work. Is it simpler though? I find this convoluted, but if this is what FME does then fine. I got confused that no writer appeared in my canvas, then realised (like 2h later!) that it was in the navigator!
> 

Yeah, sorry.  That is kind of confusing.  (I am just used to it.)
Adding a writer can happen, with no FeatureTypes, as you found out.  You just have to add them yourself manually, one by one, or import them from a dataset, or copy them from a reader.  Glad you figured that out.

In the future, we want this to be smoother by adding the two options directly into the Writer settings box, so you never have to have this blank canvas to add things to.  But we didn't have time to add that before FME 2020.0 shipped.  Hopefully in FME 2020.1 or something soon.


> **Option B** works fine. The schema exposes `children` and `parents` but we mapped those to `cityjson_parents` and `cityjson_children` because those are special fields that are not attributes. Perhaps remove? Rest is fine for that option.
> 

Thanks for this feedback.  I have fixed the code, the metafile, etc. to all do as you say.  Those are now called just like you want, and are not exposed as user attributes.  (They show up on the "format attributes" tab of the writer FeatureType settings.)

> **Option D** crashes for me. Output console below. Do I have to pick some schemas somewhere?
> 
UGH.  This was my typo.  I fixed this bug and pushed it to the code.  Sorry!

**Comment by KevinWiebe** [comment] 2020-03-06 00:46
> **Option A** works too. I also expected a writer in my canvas as Hugo.
> 
Sorry to you as well!

> 
> **UPDATE**
> **Option C** crashes for me on the [Railway data](https://3d.bk.tudelft.nl/opendata/cityjson/1.0/LoD3_Railway.json). See the log and screenshot of my Workbench below. It probably has to do with the donut visitor, see below.
> 

Yeah, I looked into this, and that is because there was a bit of brittle code in the writer.
FMECityJSONGeometryVisitor::semanticTypeAllowed()
- This method looks up a featuretype in a std::map, and if it does not find it, crashes.
- I fixed this code to be a bit more resilient.  If it can't find it, it will log a warning and skip it.  Update your code and see the fix.
- The dataset you were using has a featuretype called "Tunnel", but that is not in the hard coded map at the top of the file fmecityjsongeometryvisitor.cpp   - I guess you can decide how to add to that map or make it more dynamic (read it from some schema files?) or figure out why Tunnel is not in there.

In general, I think all the CityJSON code might be written a bit better to catch any exceptions that are thrown and log meaningful error messages.  In cases like this, thrown exceptions are just caught way up in FME and it has no idea what is going wrong.

> **Option D** crashes with the same error as for Hugo.
Yeah, my bad.  That bug is fixed.

**Comment by KevinWiebe** [comment] 2020-03-11 20:48
I'm going to say that this issue is fixed now, right?  Re-open if you disagree.

**Closed by KevinWiebe** 2020-03-11 20:48 UTC
